"""add is edited column to track revisions of articles

Revision ID: 109b92e34c6d
Revises: 6c6df8e0b53b
Create Date: 2020-04-16 16:21:58.367413

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '109b92e34c6d'
down_revision = '6c6df8e0b53b'
branch_labels = None
depends_on = None


def upgrade():
    pass
    # ### commands auto generated by Alembic - please adjust! ###
    # op.add_column('article', sa.Column('is_edited', sa.Boolean(), nullable=True))
    # op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=20), nullable=False))
    op.drop_column('article', 'is_edited')
    # ### end Alembic commands ###
