"""Adding linkedin column, removing username

Revision ID: 6c6df8e0b53b
Revises: cef1e14382f7
Create Date: 2020-04-14 13:40:14.450976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c6df8e0b53b'
down_revision = 'cef1e14382f7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('linkedin', sa.String(length=100), nullable=True))
    op.drop_column('user', 'username')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('username', sa.VARCHAR(length=20), nullable=False))
    op.drop_column('user', 'linkedin')
    # ### end Alembic commands ###
