"""Initial update

Revision ID: cef1e14382f7
Revises: 
Create Date: 2020-04-14 13:32:27.778680

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cef1e14382f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('article_id', sa.Integer(), nullable=False),
    sa.Column('is_ready_for_release', sa.Boolean(), nullable=True),
    sa.Column('is_released', sa.Boolean(), nullable=True),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('preview', sa.String(length=200), nullable=False),
    sa.Column('posted', sa.DateTime(), nullable=False),
    sa.Column('edited', sa.DateTime(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('user_bio')
    op.drop_table('post')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('aticle_id', sa.INTEGER(), nullable=False),
    sa.Column('is_ready_for_review', sa.BOOLEAN(), nullable=True),
    sa.Column('is_released', sa.BOOLEAN(), nullable=True),
    sa.Column('title', sa.VARCHAR(length=100), nullable=False),
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('preview', sa.VARCHAR(length=200), nullable=False),
    sa.Column('posted', sa.DATETIME(), nullable=False),
    sa.Column('edited', sa.DATETIME(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.CheckConstraint('is_ready_for_review IN (0, 1)'),
    sa.CheckConstraint('is_released IN (0, 1)'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_bio',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('username', sa.INTEGER(), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.ForeignKeyConstraint(['username'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('article')
    # ### end Alembic commands ###
